title: My Awesome Blog
description: A delightful blend of code and whimsy
baseurl: ""

theme: jekyll-theme-chirpy
language: en

author:
  name: scratchsay
  bio: Digital wanderer exploring code and creativity
  location: Cosmic Realm

social:
  - title: GitHub
    url: https://github.com/scratchsay
  - title: Twitter
    url: https://twitter.com/scratchsay

plugins:
  - jekyll-feed
  - jekyll-sitemap
